name: Build Windows EXE

# 当打 tag（v*）时触发
on:
  push:
    tags:
      - 'v*'

# 赋予 GITHUB_TOKEN 写仓库内容的权限，才能创建 Release
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests beautifulsoup4

      - name: 打包为单文件 exe
        run: |
          # 指定输出名称 extract_juejin_article.exe
          pyinstaller --noconsole --onefile main.py --name extract_juejin_article

      - name: 列出 dist 目录确认文件
        run: dir dist

      - name: 发布到 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # 一定要和上一步产物名一致
          files: dist\\extract_juejin_article.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
