name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'   # 只有打tag时才触发，比如 v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests beautifulsoup4

      - name: 打包为单文件 exe
        run: |
          pyinstaller --noconsole --onefile extract_juejin_article.py

      - name: 上传 exe 到 Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/extract_juejin_article.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
